# This is a basic workflow to help you get started with Actions
name: TestTriggerBuildJenkinsJob

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build TriggerFromGitHub
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
            
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@v0.0.2
        with:
          url: "https://05c3-2402-9d80-24a-1c00-5cd2-3245-8867-6c84.ngrok-free.app/"
          user: "admin"
          token: "117fbdc1fab405340c1918bf5ed52949e9"
          job: "TriggerWithGIthubAction"
